# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:bin/curl-7.50.2/bin/

export PATH

# Load other profile
source $HOME/.profile
